=== Getting Started with Micronaut Framework and GraalVM

Starting with Micronaut framework 2.2, any Micronaut application can be built into a native image using the Micronaut Gradle or Maven plugins. To get started, create a new application.

.Creating a GraalVM Native Microservice
[source,bash]
----
$ mn create-app hello-world
----

You can use `--build maven` for a Maven build.

==== Building a Native Image Using Docker

To build your native image using Docker and Gradle, run:

.Building a Native Image with Docker and Gradle
[source,bash]
----
$ ./gradlew dockerBuildNative
----

To build your native image using Docker and Maven, run:

.Building a Native Image with Docker and Maven
[source,bash]
----
$ ./mvnw package -Dpackaging=docker-native
----

==== Building a Native Image Without Using Docker

To build your native image without using Docker, install a GraalVM JDK. The easiest way to install GraalVM on Linux or Mac is to use https://sdkman.io/[SDKMAN!]. For other installation options, visit the https://www.graalvm.org/downloads/[Downloads page].

.Installing GraalVM {graalVersion} with SDKMAN!
[source,bash,subs="attributes+"]
----
$ sdk install java {graalVersion}-graal
$ sdk use java {graalVersion}-graal
----

Once you install GraalVM, the `native-image` tool becomes available.

===== Gradle

You can build a native image with Gradle by running the `nativeCompile` task:

.Creating a native image with Gradle
[source,bash]
----
$ ./gradlew nativeCompile
----

The native executable file is created in the _build/native/nativeCompile_ directory.
You can then run it from that directory: `./build/native/nativeCompile/hello-world`.

It is possible to pass additional build arguments to `native-image` using the https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html[Gradle plugin for Native Image building].
Add the following configuration to _build.gradle_:

.build.gradle
[source,groovy]
----
graalvmNative {
    binaries {
        main {
            imageName.set('myApp') // <1>
            buildArgs.add('-Ob') // <2>
        }
    }
}
----
<1> Use `imageName.set()` to specify a custom name.
<2> Use `buildArgs.add()` to pass extra build arguments to `native-image`. For example, `-Ob` enables the quick build mode.

===== Maven

To create a native image with Maven, use the `native-image` packaging format:

.Creating a native image with Maven
[source,bash]
----
$ ./mvnw package -Dpackaging=native-image
----

The native executable file is created in the _target/_ directory.
You can then run it from that directory: `./target/hello-world`.

It is possible to pass additional build arguments to `native-image` using the https://graalvm.github.io/native-build-tools/latest/maven-plugin.html[Maven plugin for Native Image building].
Declare the plugin as following:

.pom.xml
[source,xml]
----
<plugin>
    <groupId>org.graalvm.buildtools</groupId>
    <artifactId>native-maven-plugin</artifactId>
    <version>${native-maven-plugin.version}</version>
    <configuration>
        <!-- <1> -->
        <imageName>myApp</imageName> 
        <buildArgs>
              <!-- <2> -->
          <buildArg>-Ob</buildArg>
        </buildArgs>
    </configuration>
</plugin>
----

<1> Use `<imageName>` to specify a custom name.
<2> Use `buildArg` to pass extra build arguments to `native-image`. For example, `-Ob` enables the quick build mode.

=== Understanding Micronaut Framework and GraalVM

The Micronaut framework itself does not rely on reflection or dynamic class loading, so it works automatically with GraalVM Native Image. However certain third-party libraries used by Micronaut may require additional input about uses of reflection.

The Micronaut framework includes an annotation processor that helps to generate reflection configuration that is automatically picked up by the `native-image` tool:

dependency:micronaut-graal[scope="annotationProcessor"]

This processor generates additional classes that implement the api:core.graal.GraalReflectionConfigurer[] interface and programmatically register reflection configuration.

For example, see the following class:

[source,java]
----
package example;

import io.micronaut.core.annotation.ReflectiveAccess;

@ReflectiveAccess
class Test {
    ...
}
----

The above example results in the public methods, declared fields, and declared constructors of `example.Test` being registered for reflective access.

If you have more advanced requirements and wish to include only certain fields or methods, use the annotation on any constructor, field, or method to include only the specific field, constructor, or method.

=== Adding Additional Classes for Reflective Access

The Micronaut framework provides several annotations to specify additional classes that should be included in the generated reflection configuration, such as:

* ann:core.annotation.ReflectiveAccess[] - An annotation that can be declared on a specific type, constructor, method, or field to enable reflective access just for the annotated element.
* ann:core.annotation.TypeHint[] - An annotation that allows to bulk configuration of reflective access to one or many types.
* ann:core.annotation.ReflectionConfig[] - A repeatable annotation that directly models the https://www.graalvm.org/reference-manual/native-image/metadata/#reflection[reflection configuration in JSON format].

The `@ReflectiveAccess` annotation is typically used on a particular type, constructor, method, or field whilst the latter two are typically used on a module or `Application` class to include classes that are needed reflectively.
See the following example from Micronaut's Jackson module with `@TypeHint`:

.Using the `@TypeHint` annotation
[source,java]
----
@TypeHint(
    value = { // <1>
        PropertyNamingStrategy.UpperCamelCaseStrategy.class,
        ArrayList.class,
        LinkedHashMap.class,
        HashSet.class
    },
    accessType = TypeHint.AccessType.ALL_DECLARED_CONSTRUCTORS // <2>
)
----

<1> The `value` member specifies which classes require reflection.
<2> The `accessType` member specifies if only class loading access is needed or whether full reflection on all public members is needed.

Alternatively, use the `@ReflectionConfig` annotation which is repeatable and allows distinct configuration per type:

.Using the `@ReflectionConfig` annotation
[source,java]
----
@ReflectionConfig(
    type = PropertyNamingStrategy.UpperCamelCaseStrategy.class,
    accessType = TypeHint.AccessType.ALL_DECLARED_CONSTRUCTORS
)
@ReflectionConfig(
    type = ArrayList.class,
    accessType = TypeHint.AccessType.ALL_DECLARED_CONSTRUCTORS
)
@ReflectionConfig(
    type = LinkedHashMap.class,
    accessType = TypeHint.AccessType.ALL_DECLARED_CONSTRUCTORS
)
@ReflectionConfig(
    type = HashSet.class,
    accessType = TypeHint.AccessType.ALL_DECLARED_CONSTRUCTORS
)
----

=== Generating Native Images

GraalVM's `native-image` command generates native images. You can use this command manually to generate your native image. For example:

.The `native-image` command
[source,bash]
----
native-image --class-path build/libs/hello-world-0.1-all.jar # <1>
----
<1> The `class-path` argument refers to the Micronaut shaded JAR.

Once the image is built, run the application using its name:

.Running the native application
[source,bash]
----
$ ./hello-world
15:15:15.153 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 14ms. Server Running: http://localhost:8080
----

As you can see, the native image startup completes in milliseconds, and memory consumption does not include the overhead of the JVM (a native Micronaut application runs with just 20MB of memory).

=== Resource File Generation

Starting with Micronaut framework 3.0, the automatic generation of the _resource-config.json_ file is now integrated into the https://github.com/micronaut-projects/micronaut-gradle-plugin[Gradle] and https://github.com/micronaut-projects/micronaut-maven-plugin[Maven] plugins.